# Generated by Django 6.0.2 on 2026-06-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('Confirmed', 'Confirmed'), ('preparing', 'preparing'), ('Ready', 'Ready'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
