# Generated by Django 6.0.6 on 2026-06-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('Confirmed', 'Confirmed'), ('preparing', 'preparing'), ('Ready', 'Ready'), ('Bill Generated', 'Bill Generated'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
